services:
  - type: web
    name: user-manager-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn user_manager.wsgi:application
    envVars:
      - key: SECRET_KEY
        value: your-secret-key
      - key: DEBUG
        value: false
      - key: DJANGO_SETTINGS_MODULE
        value: user_manager.settings
