# Generated by Django 5.2.4 on 2025-07-08 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('normal', 'Normal User'), ('admin', 'Admin')], default='normal', max_length=10),
        ),
    ]
